name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-dotnet@v4.1.0
      - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage/opencover.xml
      - name: Build for Windows x64 
        run: dotnet publish ./src/Leonardo.Web/Leonardo.Web.csproj --self-contained true --output ./win-x64/fibonacci -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishReadyToRun=true
      - name: Build for Linux x64 
        run: dotnet publish ./src/Leonardo.Web/Leonardo.Web.csproj --self-contained true --output ./linux-x64/fibonacci -c Release -r linux-x64 /p:PublishSingleFile=true /p:PublishReadyToRun=true
      - name: Upload WebApp1 Windows x64
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Publish win-x64 Fibonacci
          path: ./win-x64/fibonacci
      - name: Upload WebApp1 Linux x64
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Publish linux-x64 Fibonacci
          path: ./linux-x64/fibonacci